DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS evento;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  Username TEXT UNIQUE NOT NULL,
  Password TEXT NOT NULL
);

CREATE TABLE evento (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  nombre TEXT NOT NULL,
  categoria TEXT NOT NULL,
  lugar TEXT NOT NULL,
  direccion TEXT NOT NULL,
  fechaInicial DATE NOT NULL,
  fechaFinal DATE NOT NULL,
  tipo TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);